ALTER FUNCTION SUMAR(@X INT, @Y INT)
RETURNS INT
AS
BEGIN
	DECLARE @RES INT;
	SET @RES = @X + @Y
	RETURN @RES
END

SELECT dbo.SUMAR(2,5)


CREATE FUNCTION CONCATENATE(@name VARCHAR(10), @lastname VARCHAR(10))
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @res VARCHAR(100);
	SET @res = CONCAT(@name, @lastname);
	RETURN @res;
END

SELECT dbo.CONCATENATE('Steven', 'Bang')
