DECLARE @mitabla TABLE (
	id INT IDENTITY(1,1), pais VARCHAR(50)
)

INSERT INTO @mitabla VALUES('MEXICO')
INSERT INTO @mitabla VALUES('PERU')
INSERT INTO @mitabla VALUES('ARGENTINA')
INSERT INTO @mitabla VALUES('COLOMBIA')
INSERT INTO @mitabla VALUES('ECUADOR')

SELECT * FROM @mitabla;


-- CREATE TABLE
CREATE TABLE #mitabla(
	id int IDENTITY(1,1),
	name VARCHAR(50), 
	lastname VARCHAR(50))

INSERT INTO #mitabla VALUES('KIRBY', 'STAR')
INSERT INTO #mitabla VALUES('LUIGI', 'BROS')
INSERT INTO #mitabla VALUES('SAMUS', 'ARAN')

SELECT * FROM #mitabla;

-- DELATE TABLE
DROP TABLE #mitabla

